# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def change_site_domain_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=settings.SITE_ID,
        defaults={
            'domain': '{{ HOST_NAME }} ',
            'name': "AwesomeGame {{ pillar['dd_server_name'] }}"
        }
    )
    Site.objects.update_or_create(
        id=2,
        defaults={
            'domain': '{{ panel_url }}',
            'name': 'AwesomeGame Panel'
        }
    )


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_site_domain_name, reverse_code=do_nothing)
    ]
